name: Push Event Workflow

on:
  push:
    branches:
      - main 
jobs:
  print_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2 

    - name: Print GitHub Event Data as JSON
      run: |
        echo "Printing JSON data for Push event"
        echo "${{ toJson(github) }}" 
